export { default as Home } from './home/Home'
export { default as NotFound } from './home/Home'
export { default as Documentation } from './documentation/Documentation'
export { default as Login } from './auth/login/Login'
export { default as Register } from './auth/register/Register'
export { default as ForgotPassword } from './auth/forgot-password/ForgotPassword'
export { default as StudyMaterials } from './study-materials/StudyMaterials'
export { default as ResetPassword } from './auth/reset-password/ResetPassword'
