export { default as Home } from './home/Home'
export { default as NotFound } from './home/Home'
export { default as Documentation } from './documentation/Documentation'
export { default as Login } from './login/Login'
export { default as Register } from './register/Register'
export { default as ForgotPassword } from './forgot-password/ForgotPassword'
